### ISSUE TITLE
TypeScript question

### ISSUE THREAD

**Issue by XeroxDev** [SinusBot/scripting-docs#16]
Hey, I have a simple question.

I wanna to write plugins in typescript instead of javascript and the types here are available for typescript, but how must I complie the source, to work with sinusbot? Currently I complied it into a bundle file.

I hope you can help me.

Kind regards,
XeroxDev

**Comment by irgendwr** [comment]
> but how must I compile the source, to work with sinusbot?

Scripts are valid JavaScript (`.js`) files that call the `registerPlugin()` function and handle everything in the `mainFunction`, as [documented](https://sinusbot.github.io/scripting-docs/) and shown in many [examples](https://github.com/SinusBot/scripts).
How you compile typescript into a valid script file is up to you.

**Comment by irgendwr** [comment]
If you want a more detailed answer to the question you need to provide your source-code and steps on how to reproduce it (i.e. how you compiled it).

**Comment by XeroxDev** [comment]
Hey @irgendwr, da ich nun auch weiß, das man hier auch Deutsch sprechen kann (was teilweise irgendwie auch Sinn macht), habe ich eine wichtige Frage bzgl dieses Issues.

Ich bin aktuell am Entwickeln der TypeScript Version von Support++

Und zwar, egal was ich versuche, ich bekomme es nicht zum laufen.

Ich bekomme immer den gleichen Fehler, habe es ebenfalls auch mit anderen webpack Konfigurationen getestet, aber es resultiert, immer in den gleichen Fehler und zwar

[Dev-Bundle]
```
PLUGIN Script support-pp returned an error (main function): ReferenceError: 'cov_g62nnhb75' is not defined
    at main (support-pp.js:121:37)
    at ScriptRunner (<anonymous>:42:5)
    at <unknown>
```

[Prod-Bundle]
```
PLUGIN Script support-pp returned an error (main function): ReferenceError: 't' is not defined
    at main (support-pp.js:1:163)
    at ScriptRunner (<anonymous>:42:5)
    at <unknown>
```

Der Link zu dem Test-Source-Code ist hier: https://github.com/Support-pp/Support-pp/tree/typescript

Kennen Sie eventuell die Gründe?

Und ich wollte ebenfalls noch melden, dass bei Ihnen in dem npm Paket 'sinusbot-scripting-engine' in den types 2 Fehler bestehen und zwar kommen diese Fehler beim bauen:

```
ERROR in [at-loader] ./node_modules/sinusbot-scripting-engine/tsd/types.d.ts:2039:17
    TS2304: Cannot find name 'Ws'.

ERROR in [at-loader] ./node_modules/sinusbot-scripting-engine/tsd/types.d.ts:2049:17
    TS2304: Cannot find name 'Db'.
```

Mit freundlichen Grüßen
XeroxDev
