### ISSUE TITLE
feat: add support for webstorm (require(): unresolved function)

### ISSUE THREAD

**Issue by LukasWestholt** [SinusBot/scripting-docs#27]
since sinusbot-scripting-engine@1.0.6 i have the problem that the require() function is not resolved anymore. Example: `const engine = require('engine');` Everything else is properly resolved. 
I use:
IDE: Webstorm 2019.1.2
node: 12.2.0
npm: 6.9.0

**Comment by irgendwr** [comment]
Works fine with the latest typings (1.0.6 is old), I can't reproduce your issue in VS Code using the latest release.

Upgrade with `npm i sinusbot-scripting-engine` and check if you can reproduce the issue.

**Comment by LukasWestholt** [comment]
I use the latest version too, and since 1.0.6 i have this little problem.

**Comment by LukasWestholt** [comment]
In 1.0.5 there was a code line: `declare var require: any;`
In 1.0.10 there is no declaration of require anymore i think.

**Comment by irgendwr** [comment]
Yes, that's correct. We should not declare require, instead you likely need to tell your IDE that require is available.

See https://stackoverflow.com/a/20148144/4884643

**Comment by LukasWestholt** [comment]
ok, require is found now, but now i have the problem that "Module 'engine' is not installed". Only module sinusbot-scripting-engine is getting found. How can i implement the single modules?

**Comment by irgendwr** [comment]
I don't use webstorm ¯\\\_(ツ)\_/¯
We have working instructions for vs code because we use vs code.
If you use a different IDE then that's your job to find out, we can't test/support every IDE ^^
If you find a solution you can add instructions for webstorm and open a pull-request to help others.

**Comment by irgendwr** [comment]
Maybe we can look into it in the future but currently I don't have time/motivation to look into how to configure webstorm for this.

Contributions/pull-request are welcome 😄

**Comment by LukasWestholt** [comment]
I've found that the "Missing module dependency" problem by the Webstorm Inspections is resolved when I place empty folders with the names of the modules (as "audio", "backend" etc.) in node_modules.
This fixes the problem. Thank you for your help. For more information about my problem and the quick-and-dirty solution see [my JetBrains Community Post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003568960-d-ts-typings-with-multiply-modules-which-i-can-t-require-).
